services:
  # Backend Service
  - type: web
    name: dudu-move-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add your MongoDB URI and other environment variables in Render dashboard
    healthCheckPath: /health

  # Static Site (Frontend) - Deploy separately to Netlify
  # This configuration is for reference only